---
- hosts: all
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_only: yes

    - name: Install required packages
      dnf:
        name:
          - python3-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - docker
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
